security:
    encoders:
        App\Entity\Yes:
            algorithm: auto
        App\Entity\User:
            algorithm: auto



    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\LoginAuth
            logout:
                path: app_logout
                target: /
                # where to redirect after logout
                # target: app_any_route
           
            

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
